name: test_universe
fixtures:
  spot_1:
    kind: Spotlight
    start_channel: 1

  strip_1_1:
    kind: RGB_Vdim
    start_channel: 7

  strip_1_2:
    kind: RGB_Vdim
    start_channel: 10

  strip_1_3:
    kind: RGB_Vdim
    start_channel: 13

  strip_1_4:
    kind: RGB_Vdim
    start_channel: 16

  strip_1_5:
    kind: RGB_Vdim
    start_channel: 19

  strip_1_6:
    kind: RGB_Vdim
    start_channel: 22

  strip_1_7:
    kind: RGB_Vdim
    start_channel: 25

  strip_1_8:
    kind: RGB_Vdim
    start_channel: 28

